<?php
/*
 * Using Duo's Web SDK
 */

include('duo_web.php');

// https://www.owasp.org/index.php/PHP_Security_Cheat_Sheet#No_Tags
function xssafe($data, $encoding='UTF-8') {
    return htmlspecialchars($data, ENT_QUOTES | ENT_HTML401, $encoding);
}
function xecho($data) {
    echo xssafe($data);
}

$attributes = $this->data['attributes'];
$username_attribute = $this->data['usernameAttribute'];

/*
 * This is something uniquely generated by you for your application and is
 * not shared with Duo.
 */
define('AKEY', $this->data['akey']);

/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard on
 * the integrations page.
 */
define('IKEY', $this->data['ikey']);
define('SKEY', $this->data['skey']);
define('HOST', $this->data['host']);

$this->includeAtTemplateBase('includes/header.php');

/*
 * Once secondary auth has completed you may log in the user
 */
if (isset($_POST['sig_response'])) {
    /*
     * Verify sig response and log in user. Make sure that verifyResponse
     * does not return NULL, if it is NOT NULL then it will return a username.
     * You can then set any cookies/session data for that username and complete
     * the login process.
     */
    $resp = Duo::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);
    if (isset($attributes[$username_attribute])) {
        $username = $attributes[$username_attribute][0];
    }
    else {
        throw new SimpleSAML_Error_BadRequest('Missing required username attribute.');
    }

    if ($resp != NULL and $resp === $username) {
        SimpleSAML_Auth_ProcessingChain::resumeProcessing($this->data['state']);
    }
    else {
        throw new SimpleSAML_Error_BadRequest('Response verification failed.');
    }
}

/*
 * Verify username and password. If the user and pass are good, then generate
 * a sig_request and load up the Duo iframe for secondary authentication.
 */
if (isset($attributes[$username_attribute])) {
    $username = $attributes[$username_attribute][0];

    // Generate sig request and then load up Duo javascript and iframe
    $sig_request = Duo::signRequest(IKEY, SKEY, AKEY, $username);

?>
    <script src="Duo-Web-v1.bundled.min.js"></script>
    <?php
        foreach ($this->data['yesData'] as $name => $value) {
            printf('<input type="hidden" id="%s" name="%s" value="%s" />',
                xssafe($name),
                xssafe($name),
                xssafe($value)
            );
        }
    ?>
    <input type="hidden" id="duo_host" value="<?php xecho(HOST); ?>">
    <input type="hidden" id="duo_sig_request" value="<?php xecho($sig_request); ?>">
    <script src="Duo-Init.js"></script>

    <iframe id="duo_iframe" frameborder="0"></iframe>
<?php

}

$this->includeAtTemplateBase('includes/footer.php');
?>
